### ISSUE TITLE
Profile twincam startup time

### ISSUE THREAD

**Issue by ericcurtin** [ericcurtin/twincam#13]
We need to profile twincam (and the rest of the camera stack before twincam even starts) further, we are going to measure by printing the uptime when we hit each of the following functions (or SDL equivalents once we port SDL sink):

```
CamApp::run
CamApp::exec
main
KMSSink::KMSSink
KMSSink::mapBuffer
KMSSink::configure
KMSSink::configurePipeline
```

Some example code of how we get uptime at millisecond precision, you can read the /proc/uptime file in Linux.

```
#include <fcntl.h>
#include <locale.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int uptime(float* up, float* elapsed) {
  int fd;
  const char* filename = "/proc/uptime";
  char buf[32];
  int n;
  if ((fd = open(filename, O_RDONLY)) == -1) {
    fputs("Error: /proc must be mounted\n", stderr);
    fflush(NULL);
    return 102;
  }

  lseek(fd, 0L, SEEK_SET);
  if ((n = read(fd, buf, sizeof buf - 1)) < 0) {
    perror(filename);
    fflush(NULL);
    return 103;
  }

  buf[n] = '\0';

  char* savelocale = strdup(setlocale(LC_NUMERIC, NULL));
  setlocale(LC_NUMERIC, "C");
  if (sscanf(buf, "%f", up) < 1) {
    setlocale(LC_NUMERIC, savelocale);
    free(savelocale);
    fputs("bad data in /proc/uptime\n", stderr);
    return 104;
  }

  static float init_time = 0;
  if (init_time) {
    *elapsed = *up - init_time;
  } else {
    init_time = *up;
    *elapsed = 0;
  }

  setlocale(LC_NUMERIC, savelocale);
  free(savelocale);
  return 0;
}

#define PRINT_UPTIME()                                                     \
  do {                                                                     \
    float up;                                                              \
    float elapsed;                                                         \
    uptime(&up, &elapsed);                                                 \
    printf("%.2f (%.2f), %s at %s:%d\n", up, elapsed, __PRETTY_FUNCTION__, \
           __FILE__, __LINE__);                                            \
  } while (0)

int main() {
  for (int i = 0; i < 10; ++i) {
    PRINT_UPTIME();
    sleep(1);
  }

  return 0;
}
```

**Comment by ericcurtin** [comment]
There is another way of getting uptime via sysinfo... But it only offers seconds... Given that we really have to get twincam to start under a second to hit our overall two second boot goal... Knowing this gives us 2 decimal places is helpful...

**Comment by ericcurtin** [comment]
Didn't expect you to spot this @kbingham :) ... Hope you had a great weekend! Was writing this to be helpful for @iamianmullins if he wants to take this task on sometime.

Thanks for the info.

I would use what you suggested. But I am not only interested in the performance of libcamera and/or application level (even though it's very important).

We need the camera's first frame to appear in less than 2 seconds from boot. This is why we read the value from /proc/uptime alternatively, we want the "start" to be from when the computer turned on because everything is important firmware + kernel + initrd + libcamera + twincam + plymouth + anything else you can think of, so some of these optimisations will actually be outside of libcamera space. So "now" being the start of uptime, helps us profile everything.

Example output from above example code:

```
4669.96 (0.00), int main() at uptime.c:61
4670.96 (1.00), int main() at uptime.c:61
4671.96 (2.00), int main() at uptime.c:61
4672.96 (3.00), int main() at uptime.c:61
4673.96 (4.00), int main() at uptime.c:61
4674.96 (5.00), int main() at uptime.c:61
4675.96 (6.00), int main() at uptime.c:61
4676.96 (7.00), int main() at uptime.c:61
4677.96 (8.00), int main() at uptime.c:61
4678.96 (9.00), int main() at uptime.c:61
```

My computer has been on ~4670 seconds.

**Comment by kbingham** [comment]
Aha that makes sense, sorry for the noise. Indeed I thought it was application (/library) startup time you were looking at.

**Comment by ericcurtin** [comment]
Honestly I really appreciate it, I am glad you took notice. You have more experience here than me, so any feedback is appreciated :smile:

**Comment by kbingham** [comment]
No worries - I put a watch on the github repository because I think it's an interesting project, (and a good use of libcamera) so happy to help wherever I can (but I don't want to get in the way :-D)

**Comment by ericcurtin** [comment]
Added as -u and -s options

**Comment by ericcurtin** [comment]
Found a much simpler example of this while looking at another codebase:

```
#include <fcntl.h>
#include <locale.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

int uptime(float* up, float* elapsed) {
  struct timespec timespec = {0, 0};
  clock_gettime(CLOCK_MONOTONIC, &timespec);
  *up = ((timespec.tv_sec * 1000000000) + timespec.tv_nsec) / 1000000000.0;
  static float init_time = 0;
  if (init_time) {
    *elapsed = *up - init_time;
  } else {
    init_time = *up;
    *elapsed = 0;
  }

  return 0;
}

#define PRINT_UPTIME()                                                     \
  do {                                                                     \
    float up;                                                              \
    float elapsed;                                                         \
    uptime(&up, &elapsed);                                                 \
    printf("%.2f (%.2f), %s at %s:%d\n", up, elapsed, __PRETTY_FUNCTION__, \
           __FILE__, __LINE__);                                            \
  } while (0)

int main() {
  for (int i = 0; i < 10; ++i) {
    PRINT_UPTIME();
    sleep(1);
  }

  return 0;
}
```

CLOCK_MONOTONIC treats start of boot as epoch on Linux.

**Comment by ericcurtin** [comment]
That's a decent idea, something interesting about CLOCK_MONOTONIC is that it starts from boot on Linux but POSIX doesn't require it to start from that point what I've read so CLOCK_BOOTTIME, might be more explicit and portable. Not that we will ever support anything other than Linux, but the explicitness is nice.
